# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rooster in the Midst
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is the start of something that could be huge. Or maybe not. Let's see.  


#baseurl: "" # the subpath of your site, e.g. /blog
baseurl: ""
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: http://roxvillerooster.github.io
twitter_username: RoxvilleRooster
github_username:  RoxvilleRooster
timezone: Canada/Eastern

# Build settings
markdown: kramdown

google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal
encoding: UTF-8