@startuml

' left to right direction

'default
top to bottom direction





rectangle Act1 as "Act 1: Prologue" {
usecase "Centralia, OK" as a1s1a
note left
Heroes assemble
end note
usecase "Montreal Airport" as a1s1b
note left
Heroes get on the plane
end note
usecase "Brawl at 1000 feet" as a1s2
note left
Heroes confront gangsters
Heroes get the Jade Qilin
Heroes land safely in NFLD
Fogg departs
end note
}

a1s1a --> a1s1b
a1s1b --> a1s2



rectangle Act2 as "Act 2: San Francisco" {
usecase "Auction" as a2s1
note left
Ling Su appears
Mingle at the Auction
Ling Su kidnapped
Heroes rescue Jade Qilin
Rochester goes gambling
JJ joins
Rochester is poisoned
Heroes bring Rochester to hospital
end note
usecase "Boom-Boom Breakfast" as a2s2
note left
Jimmy brings room service
Heroes move Bomb
Heroes rescue Innocents
Heroes talk
Heroes go to Chinatown
Costa researches Poison
Costa and Billy visit Herbalist
Costa and Billy notice a Spy
JJ and Trace visit Gambling Hall
JJ and Trace talk to Xie Meiying
Assassins kill Xie
JJ and Trace chase Assassins
end note
usecase "Chinatown Chase" as a2s3
note left
Heroes chase Villains
JJ and Trace catch Hitnan and Big Fella
Cost chases Spy
Billy shadows Spy
end note
usecase "Next?" as a2s4
note left

end note
}

a2s1 --> a2s2
a2s2 --> a2s3
a2s3 --> a2s4


rectangle Act3 as "Act 3: Heart Attack" {
usecase "Race to the island" as a3s1
note left
Good weather favors heroes
Nazi boats attack
end note
usecase "Ritual" as a3s2
note left
Scanlan and Brown argue
Preparation for ritual
Heroes arrive just as the ritual starts
end note
usecase "Get the totem" as a3s3
note left
Dramatic task to disrupt the ritual
end note
usecase "Safe harbor" as a3s4
note left
TBD
end note
}

a3s1 --> a3s2
a3s2 --> a3s3
a3s3 --> a3s4


Act1 --> Act2 
Act2 --> Act3
