= Third Hand

== Morrison's house

* Heroes find Morrison dead
* Heroes confront the Thuggee cultists
* Just as the heroes close in on the heroes, they all experience a blackout.
It is like the lights go out in the house briefly - its a supernatural darkness.
** Fogg falls from the balcony but - unlike the others - he hear's the words in Hindi "My servant will not fail me. I will have the hand of Kali."footnote:[https://www.google.com/search?q=google+translate&rlz=1C1CHBF_enCA990CA990&oq=google+translate&aqs=chrome.0.69i59j69i64l2.3023j0j7&sourceid=chrome&ie=UTF-8]

____
mera sevak mujhe niraash nahin karega.
mere paas kaalee ka haath hoga.
____

Fogg sees a pair of piercing supernatural eyes, framed by the face of a beautiful woman.
It is this woman that says the words.

Next, when Fogg regains consciousness, he is falling a Townsend is there to catch him.

The Thuggee leader leaps to the next house, slides down the drain pipe, and then breaks for a lane way where his motorcycle stands.

The Thuggee leader 
The motorcycles of his accomplices are nearby and he stops briefly to topple them over.

There is a station wagon nearby.
The heroes can go back to their car or hotwire the station wagon.

He also has another accomplice, a handmaiden of the Naga. 
She attempts to stay out of sight, aid the Thuggee and hinder the players.
If the Thuggee Leader is caught, she will continue the work.

Back at the house, the heroes find the journal.
The will also hear a tick-tick-tick.
The Thuggee leader planted a crude timer bomb in the house. The bomb is attached to the bottom of the drawing table with an adhesive.

