= Savage Old-School Fantasy
:toc:

== About the old-school fantasy game

This campaign is an attempt to get close to emulating an "old school" dungeon crawl experience using the Savage Worlds (SWADE) rules. 
The goal is to reproduce many of the best elements of the old school game play and, at the same, enjoy Savage Worlds' fast-furious-fun play style.

// We'll use Greg Gillespie's Barrowmaze (and the village of the Helix) as the mainstays of the setting.
Most sessions will run as a short foray into a "dungeon". 
Adventurers who attempt to sleep or make camp in the dungeon do not typically return to tell tales. 
Your treasure hunter is, of course, welcome to try camping in a dungeon...    
// But they should feel free to go ahead and try this out.

Random encounters and wandering monsters will often be resolved using the quick combat rules.
As a Savage Worlds GM, we can hand wave _most_ resource management unless it makes the game story more interesting.   
We'll manage resources for 

* ammunition for allies
* light sources
* power points

For experience, I want to use the Gold & Glory "In it for the Gold" setting rule, which shift how we handle advancement.

// As Savage Worlds does not require the killing of monsters or acquisition of treasure for character advancement, I plan to scale down the number of combats, eliminating ones that I see as less meaningful, and there will be somewhat less treasure.
// There are traps but they tend to be less lethal to a Savage Worlds novice-level PC than they were to a first-level B/X magic-user.

You are welcome to hire and employ henchmen and hirelings (Savage Worlds allied extras). 
Players will control these extras in combat; make sure that your PCs treat the henchmen and hirelings fairly or they may turn (sneak away, run at a critical time, steal, or worse).

There is no need for a player to serve as mapper or caller.

// .Setting rules:
// * Blood & Guts
// * Critical Failures
// * Gritty Damage
// * Joker's Wild


.References:
* link:https://www.drivethrurpg.com/product/283156/GoldGlory-Seven-Deadly-Dungeons-Savage-Worlds-Adventure-Edition["Gold & Glory: Seven Deadly Dungeons (Savage Worlds Adventure Edition)]
* link:https://goodbadskinny.blogspot.com/2017/01/savage-warhammer.html[Savage Warhammer]
* link:https://www.drivethrurpg.com/product/273116/The-Tomb-of-Xenophon-MicroDungeon-Adventure-Savage-Worlds?filters=45582_0_1600_0_0[The Tomb of Xenophon: Micro-Dungeon Adventure (Savage Worlds)]
* link:https://www.drivethrurpg.com/product/265837/Tyrnador-JumpStart[Tyrnador JumpStart]
* link:https://www.drivethrurpg.com/product/275399/Icy-Belly-of-Fillion-Manor[Icy Belly of Fillion Manor]

.OSR Resources
* link:http://www.drivethrurpg.com/product/139762/Barrowmaze-Complete[Barrowmaze Complete]
* link:http://www.barrowmaze.com/meatshields[Meatshields! Hireling and Henchman Generator]

== Wild draw dungeon

The dungeon deck has 36 cards.

.Prepare the dungeon deck by removing these cards
* face cards
* aces
* jokers

When you've drawn all the cards, shuffle the deck.

. Draw 3 cards face up and put them in row.
. Evaluate the cards for room size and exits.
+ 
[NOTE]
====
.If the complex is a primarily man-made structure (e.g., dungeon or tomb) and 
* most cards are black, the exits are doors. 
* most cards are red, the exits are passages (e.g., archways). 

.If the complex is a primarily a natural structure, such as a cavern or cave system and 
* most cards are black, the exits are doors,  the “room” is a confluence of narrow tunnels; only draw tunnels leading to the appropriate number of exits.
Bear in mind the general size of the area but you're not bound to the dimensions. + 
* most cards are red, the “room” is a cave with the size and exits that are indicated by th cards . 
====
+ 
Card 1::
Room width;;
The card value determines the width of the room in inches
Card 2::
Room length:;;
The card value determines the length of the room in inches
Card 3::
Number of exits;;
2 to 5 = 1 exit; 6 to 8 = 2 exits; 9 or 10 = 3 exits
. Determine the general contents of the room. + 
The suit of each card determines the content of the room. 
Black cards indicate nothing special whereas red cards indicate something important: 
* Diamonds represent _treasure_
* Hearts represent _hazards_ (e.g., monster and traps)
. Determine specific contents of the room.
The GM can decide the contents of the room on the fly or the contents can be predetermined (e.g., defined in tables). 
+   
TIP: You can create a dungeon by assigning a specific content for each red card.

== Village buildings

. Village square
. General store "Turgen's Trade Goods"
. Smithy "The Axe and Anvil"
. Guild hall for mercenaries
. Depot for merchants "Silver Standard Merchant Caravan Company" 
. Shrine to St. Ygg
. Jeweler and moneylender "The Rosy Quartz"
. Tavern "The Brazen Strumpet"
. Gambling hall and brother "The Foul Pheasant"
. Tower of the wizard
. Bowyer/fletcher
. Mill
. Barrowmaze
. Statue of Herne
. Ancient ruins
. Ironguard Motte

