= Savage Old-School Fantasy
:toc:

== About the old-school fantasy game

This campaign is an attempt to get close to emulating an "old school" dungeon crawl experience using the Savage Worlds (SWADE) rules. 
The goal is to reproduce many of the best elements of the old school game play and, at the same, enjoy Savage Worlds' fast-furious-fun play style.

// We'll use Greg Gillespie's Barrowmaze (and the village of the Helix) as the mainstays of the setting.
Most sessions will run as a short foray into a "dungeon". 
Adventurers who attempt to sleep or make camp in the dungeon do not typically return to tell tales. 
Your treasure hunter is, of course, welcome to try camping in a dungeon...    
// But they should feel free to go ahead and try this out.

Random encounters and wandering monsters will often be resolved using the quick combat rules.
As a Savage Worlds GM, we can hand wave _most_ resource management unless it makes the game story more interesting.   
We'll manage resources for 

* ammunition for allies
* light sources
* power points

For experience, I want to use the Gold & Glory "In it for the Gold" setting rule, which shift how we handle advancement.

// As Savage Worlds does not require the killing of monsters or acquisition of treasure for character advancement, I plan to scale down the number of combats, eliminating ones that I see as less meaningful, and there will be somewhat less treasure.
// There are traps but they tend to be less lethal to a Savage Worlds novice-level PC than they were to a first-level B/X magic-user.

You are welcome to hire and employ henchmen and hirelings (Savage Worlds allied extras). 
Players will control these extras in combat; make sure that your PCs treat the henchmen and hirelings fairly or they may turn (sneak away, run at a critical time, steal, or worse).

There is no need for a player to serve as mapper or caller.

// .Setting rules:
// * Blood & Guts
// * Critical Failures
// * Gritty Damage
// * Joker's Wild


.References:
* link:https://www.drivethrurpg.com/product/283156/GoldGlory-Seven-Deadly-Dungeons-Savage-Worlds-Adventure-Edition["Gold & Glory: Seven Deadly Dungeons (Savage Worlds Adventure Edition)]
* link:https://goodbadskinny.blogspot.com/2017/01/savage-warhammer.html[Savage Warhammer]
* link:https://www.drivethrurpg.com/product/273116/The-Tomb-of-Xenophon-MicroDungeon-Adventure-Savage-Worlds?filters=45582_0_1600_0_0[The Tomb of Xenophon: Micro-Dungeon Adventure (Savage Worlds)]
* link:https://www.drivethrurpg.com/product/265837/Tyrnador-JumpStart[Tyrnador JumpStart]
* link:https://www.drivethrurpg.com/product/275399/Icy-Belly-of-Fillion-Manor[Icy Belly of Fillion Manor]

.OSR Resources
* link:http://www.drivethrurpg.com/product/139762/Barrowmaze-Complete[Barrowmaze Complete]
* link:http://www.barrowmaze.com/meatshields[Meatshields! Hireling and Henchman Generator]

== Character creation

=== Races

Humans, dawrves, and half-folk are standard player races.
See SWADE for racial characteristics.

NOTE: Elves are powerful - consult the GM if you want to play an elf, but do not get your hopes up.

=== Traits

As per SWADE.
Allocate 12 skills points.


By default a character knows one language per Smarts die type, starting with his native language.
For example, a character with Smarts d8, knows three languages.

NOTE: The *Reputation* trait represents the fame of the character. 
Your _Reputation_ starts at 0, unless it is modified by Edges and Hindrances.

=== Gear

Characters start with a set of clothes, a backpack, and all the gear they can buy with their starting money, equal to 500 cp. 


== Check for wandering monsters
Draw a card from the Action Deck, one per group of heroes (in case they split up).
A random encounter happens only with a Club or a Joker.
If the encounter has already happened, ignore it unless the encounter is
marked as Repeatable. 

NOTE: Not all encounters are with
creatures.

An adventure will have a table of Wandering Monsters, based on a card drawn from the Action Deck.

The unit of measure is the abstract “room”, which means the time an average party of adventurers needs to carefully explore one room. 

In the wilderness, you can consider it equal to one “encounter”. 

For ease of use, draw a card for every room the heroes explore, alternately checking for lights and one for wandering monsters.


== Illumination
The GM uses the illumination rules of Savage Worlds and
the following rules:

=== Light Checks
The GM will ask you to make a Light Check for every perishable source of light you have (e.g., torches and lanterns). 

. Draw a card from the Action Deck.
On a club, cancel a Durability point from your source of light. 

If the Durability drops to zero, the light source is exhausted. 

You can refill a lantern using an oil flask, restoring Durability to the maximum.

[cols="1,2"]
|===
| Torch | Durability 1
| Lantern | Durability 2
|===

=== Snuff Out Checks

In a dramatic situation (e.g., combat or chase), a character who is holding a light source must
check to if he drops the light whenever one of the following conditions arise:

* the character rolls a 1 on a Trait roll
* the character is hit hard (i.e., at least Shaken by a damaging effect)

The player draws a card from the Action Deck. 
On a club, the light falls and is extinguished. 
You can light it again.
However, if the club is also a face card, the lantern breaks.


=== Making Light in Darkness 

A character with a torch or lantern and flint and steel can light a source of light in two rounds, one with an Agility roll. 
Without flint and steel, you can try with two stones, but this requires five minutes and a Survival (-2) roll.
The cantrip power can light a torch or a lantern in one round.

////
== Light and darkness

Darkness:: 
Most dungeons are Pitch Darkness (-6 to most actions). 
A candle, torch, or lantern is considered enough lighting (i.e., no illumination penalties).
Duration:: 
A candle, torch, and lantern last a variable amount of time, represented by the usage die.
+
[cols="30%,70%"]
|===
| Light source | Usage die 

| Candle 
a| d8 + 
Candle blows out if you run or roll snake eyes
| Lantern | d8 
| Torch | d6 

|===

Light check::
Each time the group enters a new room after the first, the character holding the
source of light rolls the usage die. 
On a result of 1, the usage die becomes a d4. + 
When the usage die is a d4 and you roll a 1, the light goes out.

Area:: 
In most cases,the source of light affects all the room/area. 
Torches and lanterns also apply Dim Lighting to adjacent rooms and areas (i.e. a -2 modifier to most actions) assuming there are no other sources of light.
////

