= Savage Old-School Fantasy
:toc:

== About the old-school fantasy game

This campaign is an attempt to get close to emulating an "old school" dungeon crawl experience using the Savage Worlds (SWADE) rules. 
The goal is to reproduce many of the best elements of the old school game play and, at the same, enjoy Savage Worlds' fast-furious-fun play style.

// We'll use Greg Gillespie's Barrowmaze (and the village of the Helix) as the mainstays of the setting.
Most sessions will run as a short foray into a "dungeon". 
Adventurers who attempt to sleep or make camp in the dungeon do not typically return to tell tales. 
Your treasure hunter is, of course, welcome to try camping in a dungeon...    
// But they should feel free to go ahead and try this out.

Random encounters and wandering monsters will often be resolved using the quick combat rules.
As a Savage Worlds GM, we can hand wave _most_ resource management unless it makes the game story more interesting.   
We'll manage resources for 

* ammunition for allies
* light sources
* power points

For experience, I want to use the Gold & Glory "In it for the Gold" setting rule, which shift how we handle advancement.

// As Savage Worlds does not require the killing of monsters or acquisition of treasure for character advancement, I plan to scale down the number of combats, eliminating ones that I see as less meaningful, and there will be somewhat less treasure.
// There are traps but they tend to be less lethal to a Savage Worlds novice-level PC than they were to a first-level B/X magic-user.

You are welcome to hire and employ henchmen and hirelings (Savage Worlds allied extras). 
Players will control these extras in combat; make sure that your PCs treat the henchmen and hirelings fairly or they may turn (sneak away, run at a critical time, steal, or worse).

There is no need for a player to serve as mapper or caller.

// .Setting rules:
// * Blood & Guts
// * Critical Failures
// * Gritty Damage
// * Joker's Wild


.References:
* link:https://www.drivethrurpg.com/product/283156/GoldGlory-Seven-Deadly-Dungeons-Savage-Worlds-Adventure-Edition["Gold & Glory: Seven Deadly Dungeons (Savage Worlds Adventure Edition)]
* link:https://goodbadskinny.blogspot.com/2017/01/savage-warhammer.html[Savage Warhammer]
* link:https://www.drivethrurpg.com/product/273116/The-Tomb-of-Xenophon-MicroDungeon-Adventure-Savage-Worlds?filters=45582_0_1600_0_0[The Tomb of Xenophon: Micro-Dungeon Adventure (Savage Worlds)]
* link:https://www.drivethrurpg.com/product/265837/Tyrnador-JumpStart[Tyrnador JumpStart]
* link:https://www.drivethrurpg.com/product/275399/Icy-Belly-of-Fillion-Manor[Icy Belly of Fillion Manor]

.OSR Resources
* link:http://www.drivethrurpg.com/product/139762/Barrowmaze-Complete[Barrowmaze Complete]
* link:http://www.barrowmaze.com/meatshields[Meatshields! Hireling and Henchman Generator]

== Wild draw dungeon

The dungeon deck has 36 cards.

.Prepare the dungeon deck by removing these cards
* face cards
* aces
* jokers

When you've drawn all the cards, shuffle the deck.

. Draw 3 cards face up and put them in row.
. Evaluate the cards for room size and exits.
+ 
[NOTE]
====
.If the complex is a primarily man-made structure (e.g., dungeon or tomb) and 
* most cards are black, the exits are doors. 
* most cards are red, the exits are passages (e.g., archways). 

.If the complex is a primarily a natural structure, such as a cavern or cave system and 
* most cards are black, the exits are doors,  the “room” is a confluence of narrow tunnels; only draw tunnels leading to the appropriate number of exits.
Bear in mind the general size of the area but you're not bound to the dimensions. + 
* most cards are red, the “room” is a cave with the size and exits that are indicated by th cards . 
====
+ 
Card 1::
Room width;;
The card value determines the width of the room in inches
Card 2::
Room length:;;
The card value determines the length of the room in inches
Card 3::
Number of exits;;
2 to 5 = 1 exit; 6 to 8 = 2 exits; 9 or 10 = 3 exits
. Determine the general contents of the room. + 
The suit of each card determines the content of the room. 
Black cards indicate nothing special whereas red cards indicate something important: 
* Diamonds represent _treasure_
* Hearts represent _hazards_ (e.g., monster and traps)
. Determine specific contents of the room.
The GM can decide the contents of the room on the fly or the contents can be predetermined (e.g., defined in tables). 
+   
TIP: You can create a dungeon by assigning a specific content for each red card.

== Check for wandering monsters
Draw a card from the Action Deck, one per group of heroes (in case they split up).
A random encounter happens only with a Club or a Joker.
If the encounter has already happened, ignore it unless the encounter is
marked as Repeatable. 

NOTE: Not all encounters are with
creatures.

An adventure will have a table of Wandering Monsters, based on a card drawn from the Action Deck.

The unit of measure is the abstract “room”, which means the time an average party of adventurers needs to carefully explore one room. 

In the wilderness, you can consider it equal to one “encounter”. 

For ease of use, draw a card for every room the heroes explore, alternately checking for lights and one for wandering monsters.


== Illumination
The GM uses the illumination rules of Savage Worlds and
the following rules:

=== Light Checks
The GM will ask you to make a Light Check for every perishable source of light you have (e.g., torches and lanterns). 

. Draw a card from the Action Deck.
On a club, cancel a Durability point from your source of light. 

If the Durability drops to zero, the light source is exhausted. 

You can refill a lantern using an oil flask, restoring Durability to the maximum.

[cols="1,2"]
|===
| Torch | Durability 1
| Lantern | Durability 2
|===

=== Snuff Out Checks

In a dramatic situation (e.g., combat or chase), a character who is holding a light source must
check to if he drops the light whenever one of the following conditions arise:

* the character rolls a 1 on a Trait roll
* the character is hit hard (i.e., at least Shaken by a damaging effect)

The player draws a card from the Action Deck. 
On a club, the light falls and is extinguished. 
You can light it again.
However, if the club is also a face card, the lantern breaks.


=== Making Light in Darkness 

A character with a torch or lantern and flint and steel can light a source of light in two rounds, one with an Agility roll. 
Without flint and steel, you can try with two stones, but this requires five minutes and a Survival (-2) roll.
The cantrip power can light a torch or a lantern in one round.

////
== Light and darkness

Darkness:: 
Most dungeons are Pitch Darkness (-6 to most actions). 
A candle, torch, or lantern is considered enough lighting (i.e., no illumination penalties).
Duration:: 
A candle, torch, and lantern last a variable amount of time, represented by the usage die.
+
[cols="30%,70%"]
|===
| Light source | Usage die 

| Candle 
a| d8 + 
Candle blows out if you run or roll snake eyes
| Lantern | d8 
| Torch | d6 

|===

Light check::
Each time the group enters a new room after the first, the character holding the
source of light rolls the usage die. 
On a result of 1, the usage die becomes a d4. + 
When the usage die is a d4 and you roll a 1, the light goes out.

Area:: 
In most cases,the source of light affects all the room/area. 
Torches and lanterns also apply Dim Lighting to adjacent rooms and areas (i.e. a -2 modifier to most actions) assuming there are no other sources of light.
////

== Village buildings

. Village square
. General store "Turgen's Trade Goods"
. Smithy "The Axe and Anvil"
. Guild hall for mercenaries
. Depot for merchants "Silver Standard Merchant Caravan Company" 
. Shrine to St. Ygg
. Jeweler and moneylender "The Rosy Quartz"
. Tavern "The Brazen Strumpet"
. Gambling hall and brother "The Foul Pheasant"
. Tower of the wizard
. Bowyer/fletcher
. Mill
. Barrowmaze
. Statue of Herne
. Ancient ruins
. Ironguard Motte

== Monsters

=== The Cursed Skeleton Knight (WC)
Once a questing knight, now a skeleton with a green glowing skull.

Attributes:: Agility d8, Smarts d8, Spirit d8, Strength d12+1, Vigor d10
Skills:: Athletics d6, Fighting d10, Intimidation d8, Notice d6, Shooting d6

Pace: 6; Parry: 7; Toughness: 13 (4)
Edges:: Improved Frenzy, Level Headed

Gear:: Black iron plate armor (+4), Red Fang greatsword (Str+d10, see below).

Special Abilities::
* Claws: Str+d4.
* Fear -1: Terrifying!
* Undead: +2 Toughness, +2 to recover from Shaken; no additional
damage from Called Shots, ignores 1 point of Wound penalties.
Doesn’t breathe, immune to poison and disease.

=== Devilbat
A boar-sized, hungry bat.

Attributes:: Agility d8, Smarts d4 (A), Spirit d6, Strength d8, Vigor d8
Skills:: Athletics d8 Fighting d8, Notice d8, Stealth d8

Pace: 1; Parry: 6; Toughness: 6

Edges:: Improved Extraction, Quick
Special Abilities::
* Bite: Str+d6.
* Flight: Pace 1.

=== Giant Lizard
A large, hungry reptile.

Attributes:: Agility d4, Smarts d4 (A), Spirit d6, Strength d10, Vigor d10
Skills:: Athletics d4, Fighting d8, Notice d6, Stealth d6

Pace: 3; Parry: 6; Toughness: 9 (2)

Special Abilities::
* Armor +2: Scaly skin.
* Bite: Str+d6.
* Rollover: On a raise with Bite, bonus damage is d10 instead of d6.


=== Moss Hulk
A colossus made of moss, roots and rocks.

Attributes:: Agility d4, Smarts d4, Spirit d8, Strength d12+2, Vigor d12
Skills:: Athletics d4, Fighting d8, Intimidation d8, Notice d4

Pace: 5; Parry: 6; Toughness: 10

Special Abilities::
* Elemental: No additional damage from Called Shots, doesn’t
breath.
* Size 2: About 8’ tall.
* Stone Fist: Str+d8.
* Weakness: Takes double damage from fire and poison.


=== Slaarp the Cold Drake (WC)
A huge lizard with blue scales and freezing breath.

Attributes:: Agility d6, Smarts d6 (A), Spirit d10, Strength d12+6, Vigor d12

Skills:: Athletics d8, Fighting d10, Intimidation d12, Notice d8, Stealth d6
Pace: 6; Parry: 7; Toughness: 17 (4)
Special Abilities::
* Armor +4: Scaly hide.
* Bite/Claws: Str+d8.
* Cold Breath: Breath Weapon inflicting 3d6 cold damage.
* Fear: Terrifying!
* Size 5 (Large): About 20’ long.
* Tail Lash: Str. Free attack against up to 2 foes at side or rear, at
no penalty.
* Weakness: Takes double damage from fire.


=== Stench Demon (WC)
A fetid, brownish cloud.

Attributes:: Agility d10, Smarts d4, Spirit d6, Strength d8, Vigor d6

Skills:: Athletics d10, Fighting d8, Notice d8, Shooting d8, Stealth d8

Pace: -; Parry: 6; Toughness: 5

Special Abilities::
* Elemental: No additional damage from Called Shots, ignores 1 point of Wound Penalties, doesn't breath, immune to disease and poison.
* Flight: Pace 10”.
* Gaseous Form: Can maneuver through non-solid surfaces, pass
through cracks, etc.
* Invulnerability: Immune to non-magical attacks.
* Vile Stench: -2 to Stealth rolls. Adjacent foes suffer -1 to all rolls.
* Wind Blast: Can choose one target or use the Cone Template, and rolls Shooting. 
Those affected make a Strength roll (-2 if hit with a raise) or are hurled 2d6”. 
Anyone who strikes a hard object takes 2d4 non-lethal damage.
* Weakness: Takes double damage from cold and air magic.

=== Stoneling
Human-sized rock elementals.

Attributes:: Agility d4, Smarts d4, Spirit d8, Strength d6, Vigor d6

Skills:: Athletics d4, Fighting d6, Notice d4, Shooting d6, Stealth d4

Pace: 4; Parry: 5; Toughness: 7 (2)

Gear:: Thrown rocks (3/6/12, Str+d4).

Special Abilities::
* Armor +2: Stone skin.
* Elemental: No additional damage from Called Shots, doesn't
breath, immune to disease and poison.
* Rock fist: Str+d4


== The party


Celestial (Ray)::
Hindrances;; One-eyed, anemic, all thumbs, outsider
Edges;; Alertness
Connections;;
* Celest and Halurr are both refugees
* Keerla and Celest are Former Business Partners

Halurr the rythmic whistler (Chuck)::
Hindrances;; Bloodthirsty, Stubborn, Outsider, All Thumbs
Edges;; AB (Miracles)
Connections;;
* Halurr is guardian to Nylan
* Celest and Halurr are both refugees 

Nylan (Aramis)::
Hindrances;; Code of honor, big mouth, all thumbs
Edges;; Quick
Connections;;
* Nylan is Halurr's ward
* Nylan and Keerla are Former Street Performers

Keerla (Devin)::
Hindrances;; Bad luck, outsider, all thumbs
Edges;; 
* AB (Magic)
* Nerves of Steel
Connections;;
* Nylan and Keerla are Former Street Performers
* Keerla and Celest are Former Business Partners