= Savage Old-School Fantasy
:toc:
:dt_phase: downtime phase

== About the old-school fantasy game

This campaign is an attempt to get close to emulating an "old school" dungeon crawl experience using the Savage Worlds (SWADE) rules. 
The goal is to reproduce many of the best elements of the old school game play and, at the same, enjoy Savage Worlds' fast-furious-fun play style.

// We'll use Greg Gillespie's Barrowmaze (and the village of the Helix) as the mainstays of the setting.
Most sessions will run as a short foray into a "dungeon". 
Adventurers who attempt to sleep or make camp in the dungeon do not typically return to tell tales. 
Your treasure hunter is, of course, welcome to try camping in a dungeon...    
// But they should feel free to go ahead and try this out.

Random encounters and wandering monsters will often be resolved using the quick combat rules.
As a Savage Worlds GM, we can hand wave _most_ resource management unless it makes the game story more interesting.   
We'll manage resources for 

* ammunition for allies
* light sources
* power points

For experience, I want to use the Gold & Glory "In it for the Gold" setting rule, which shift how we handle advancement.

// As Savage Worlds does not require the killing of monsters or acquisition of treasure for character advancement, I plan to scale down the number of combats, eliminating ones that I see as less meaningful, and there will be somewhat less treasure.
// There are traps but they tend to be less lethal to a Savage Worlds novice-level PC than they were to a first-level B/X magic-user.

You are welcome to hire and employ henchmen and hirelings (Savage Worlds allied extras). 
Players will control these extras in combat; make sure that your PCs treat the henchmen and hirelings fairly or they may turn (sneak away, run at a critical time, steal, or worse).

There is no need for a player to serve as mapper or caller.

// .Setting rules:
// * Blood & Guts
// * Critical Failures
// * Gritty Damage
// * Joker's Wild


.References:
* link:https://www.drivethrurpg.com/product/283156/GoldGlory-Seven-Deadly-Dungeons-Savage-Worlds-Adventure-Edition["Gold & Glory: Seven Deadly Dungeons (Savage Worlds Adventure Edition)]
* link:https://goodbadskinny.blogspot.com/2017/01/savage-warhammer.html[Savage Warhammer]
* link:https://www.drivethrurpg.com/product/273116/The-Tomb-of-Xenophon-MicroDungeon-Adventure-Savage-Worlds?filters=45582_0_1600_0_0[The Tomb of Xenophon: Micro-Dungeon Adventure (Savage Worlds)]
* link:https://www.drivethrurpg.com/product/265837/Tyrnador-JumpStart[Tyrnador JumpStart]
* link:https://www.drivethrurpg.com/product/275399/Icy-Belly-of-Fillion-Manor[Icy Belly of Fillion Manor]

.OSR Resources
* link:http://www.drivethrurpg.com/product/139762/Barrowmaze-Complete[Barrowmaze Complete]
* link:http://www.barrowmaze.com/meatshields[Meatshields! Hireling and Henchman Generator]

== Character creation

=== Races

Humans, dawrves, and half-folk are standard player races.
See SWADE for racial characteristics.

NOTE: Elves are powerful - consult the GM if you want to play an elf, but do not get your hopes up.

=== Traits

As per SWADE.
Allocate 12 skills points.


By default a character knows one language per Smarts die type, starting with his native language.
For example, a character with Smarts d8, knows three languages.

NOTE: The *Reputation* trait represents the fame of the character. 
Your _Reputation_ starts at 0, unless it is modified by Edges and Hindrances.

=== Gear

Characters start with a set of clothes, a backpack, and all the gear they can buy with their starting money, equal to 500 cp. 


== Check for wandering monsters
Draw a card from the Action Deck, one per group of heroes (in case they split up).
A random encounter happens only with a Club or a Joker.
If the encounter has already happened, ignore it unless the encounter is
marked as Repeatable. 

NOTE: Not all encounters are with
creatures.

An adventure will have a table of Wandering Monsters, based on a card drawn from the Action Deck.

The unit of measure is the abstract “room”, which means the time an average party of adventurers needs to carefully explore one room. 

In the wilderness, you can consider it equal to one “encounter”. 

For ease of use, draw a card for every room the heroes explore, alternately checking for lights and one for wandering monsters.


== Illumination
The GM uses the illumination rules of Savage Worlds and
the following rules:

=== Light Checks
The GM will ask you to make a Light Check for every perishable source of light you have (e.g., torches and lanterns). 

. Draw a card from the Action Deck.
On a club, cancel a Durability point from your source of light. 

If the Durability drops to zero, the light source is exhausted. 

You can refill a lantern using an oil flask, restoring Durability to the maximum.

[cols="1,2"]
|===
| Torch | Durability 1
| Lantern | Durability 2
|===

=== Snuff Out Checks

In a dramatic situation (e.g., combat or chase), a character who is holding a light source must
check to if he drops the light whenever one of the following conditions arise:

* the character rolls a 1 on a Trait roll
* the character is hit hard (i.e., at least Shaken by a damaging effect)

The player draws a card from the Action Deck. 
On a club, the light falls and is extinguished. 
You can light it again.
However, if the club is also a face card, the lantern breaks.


=== Making Light in Darkness 

A character with a torch or lantern and flint and steel can light a source of light in two rounds, one with an Agility roll. 
Without flint and steel, you can try with two stones, but this requires five minutes and a Survival (-2) roll.
The cantrip power can light a torch or a lantern in one round.

== Phases of the game

A typical game is divided into two phases: the _adventuring phase_, which is where the meat of the scenario happens, and the _downtime phase_, which is at the end of the scenario and before the start of the next adventuring phase.

=== Adventure phase



=== Downtime phase

During each {dt_phase}, the GM awards each player one activity point.

You use activity points to perform tasks, which we call _prolonged tasks_ that are important to you.
At the completion of a prolonged task, you receive the associated effect.

// examples of tasks

For each activity point that you spend, the character can undertake an activity in a prolonged task.
Most prolonged tasks also have a monetary cost.

TIP: If you have an activity point and no money, you may need to consider helping someone else perform a prolonged task (see <<#combined_effort,below>>).


// To complete a prolonged task, you need to complete 4 activities.


NOTE: Typically you do not complete a prolonged task in one {dt_phase}.

.Starting a prolonged task
. Identify the prolonged task (and desired effect).
. Spend 1 activity point.
. Make a trait roll associated with the activity/prolonged task. 
See <<#activity_roll,Activity trait rolls and results>>.

.Continuing a prolonged task
. Identify the prolonged task that you are continuing.
. Spend 1 activity point.
. Make the trait roll associated with the activity/prolonged task. 
See <<#activity_roll,Activity trait rolls and results>>.

[[activity_roll]]
.Activity trait rolls and results
[cols="1,2"]
|===
| Trait Roll | Result
| Fumble | Prolonged task fails completely and ends
| Failure | No progress
| Success | Add 1 task token toward the progress of the prolonged task
| Raise | Add 1 task token for success and add 1 token for each raise toward the progress of the prolonged task
|===

[[pt_table]]
.Prolonged tasks table
|===
| Activity | Cost | Trait roll | Effect

| Craft an item 
| 50% of the item cost
| Repair (-1 per 500 cp cost of the item, Qualities included)
| An item is crafted. 
It can have one Quality.
// TK@FUP on Quality

| Increase an arcane power
| 500 cp x (power points already
gained in this way +1)
// TK@FUP on currency
| Arcane skill (-1 per power point gained in this way)
| The character permanently increases his power points by 1.


| Splash money around
| Current Reputation * 500 cp
| Persuasion 
| Increase Reputation score by 1.
// TK@FUP test this because it may get out of hand; also consequences!

| Manage stronghold
| None 
| Smarts (-2)
// TK@FUP why the negative?
| One of the stronghold's structures, during this
{dt_phase} only, is considered two ranks higher
// TK@FUP not sure why this is useful

| Train in a skill 
| Skill die x 250 cp 
| Linked attribute (-1 per current die type of the
skill)
+ must find a trainer
| 
The character improves the chosen skill by one die type. 
+ 
A skill can only be improved by one die type in this way.  
+ 
If you improve a skill by normal means while you are in the
middle of a prolonged task of skill training you lose all the gained progress benefits.

| Train an attribute
|
|
|


| Train a protege 
| 1000 cp 
// TK@FUP on currency
| Spirit (-2)
| You gains a Novice Extra character, nominally under your control. 
You can train the same protege a second time, making that character a Sidekick as per the edge.
|===


// The Activity List is generic - feel free customize it.

// Speeding Up. The character can “buy” extra Task rolls in the same Activity point use, by spending another 50% of the cost.
//TK@FUP do not understand this

[[combined_effort]]
.Working together on a prolonged task
****
With the GM's consent, multiple characters can team up to perform the same prolonged task.
The task tokens you earn go into a shared pool toward the progress of the prologed task.

NOTE: Only one character can directly benefit from the effect of the prolonged task. 
****

// awarding ap

NOTE: You cannot accumulate and hoard activity points - you spend them in the downtime phase that the GM awards them.








////
== Light and darkness

Darkness:: 
Most dungeons are Pitch Darkness (-6 to most actions). 
A candle, torch, or lantern is considered enough lighting (i.e., no illumination penalties).
Duration:: 
A candle, torch, and lantern last a variable amount of time, represented by the usage die.
+
[cols="30%,70%"]
|===
| Light source | Usage die 

| Candle 
a| d8 + 
Candle blows out if you run or roll snake eyes
| Lantern | d8 
| Torch | d6 

|===

Light check::
Each time the group enters a new room after the first, the character holding the
source of light rolls the usage die. 
On a result of 1, the usage die becomes a d4. + 
When the usage die is a d4 and you roll a 1, the light goes out.

Area:: 
In most cases,the source of light affects all the room/area. 
Torches and lanterns also apply Dim Lighting to adjacent rooms and areas (i.e. a -2 modifier to most actions) assuming there are no other sources of light.
////

