= Savage Worlds Old-School Fantasy
:toc:

== About the old-school fantasy game

This campaign is an attempt to get close to emulating an "old school" dungeon crawl experience using the Savage Worlds (SWADE) rules. 
The goal is to reproduce many of the best elements of the old school game play and, at the same, enjoy Savage Worlds' fast-furious-fun play style.

.Genre
****
In terms of the the _Savage Worlds Adventure Edition Fantasy Companion_ (FC), the genre and tone is a combination of "Low Fantasy" and "Dark Fantasy" but I also want to minimize the number of setting rules in play.

.The setting rules we use are:
* Betrayal
// * Conviction
* Downtime (&#x2020;)
* Dynamic Backlash
* Giant Foes
* Hard Choices (&#x2021;)
// * High Adventure
// * Villainous Conviction
// * Gritty Damage
// * Skill Specialization
// * Low Power (&#x2020;)


****

// We'll use Greg Gillespie's Barrowmaze (and the village of the Helix) as the mainstays of the setting.
Most sessions will run as a short foray into a "dungeon". 
Adventurers who attempt to sleep or make camp in the dungeon do not typically return to tell tales. 
Your treasure hunter is, of course, welcome to try camping in a dungeon...    
// But they should feel free to go ahead and try this out.

Random encounters and wandering monsters will often be resolved using the quick combat rules.
As a Savage Worlds GM, we can hand wave _most_ resource management unless it makes the game story more interesting.   
We'll manage resources for 

* ammunition for allies
* light sources 
* power points

// For experience, I want to use the Gold & Glory "In it for the Gold" setting rule, which shift how we handle advancement.

// As Savage Worlds does not require the killing of monsters or acquisition of treasure for character advancement, I plan to scale down the number of combats, eliminating ones that I see as less meaningful, and there will be somewhat less treasure.
// There are traps but they tend to be less lethal to a Savage Worlds novice-level PC than they were to a first-level B/X magic-user.

You are welcome to hire and employ henchmen and hirelings (Savage Worlds "allied extras"). 
As a player, you control these extras in combat.
If your PC does not treat the henchmen and hirelings with fairness, the GM can take control of these NPCs and they may turn (sneak away, run at a critical time, steal, or worse).

There is no need for a player to serve as mapper or caller.

// .Setting rules:
// * Blood & Guts
// * Critical Failures
// * Gritty Damage
// * Joker's Wild


.References:
* Savage Worlds Adventure Edition Fantasy Companion (FC)
* link:https://www.drivethrurpg.com/product/283156/GoldGlory-Seven-Deadly-Dungeons-Savage-Worlds-Adventure-Edition["Gold & Glory: Seven Deadly Dungeons (Savage Worlds Adventure Edition)]
* link:https://goodbadskinny.blogspot.com/2017/01/savage-warhammer.html[Savage Warhammer]
* link:https://www.drivethrurpg.com/product/273116/The-Tomb-of-Xenophon-MicroDungeon-Adventure-Savage-Worlds?filters=45582_0_1600_0_0[The Tomb of Xenophon: Micro-Dungeon Adventure (Savage Worlds)]
* link:https://www.drivethrurpg.com/product/265837/Tyrnador-JumpStart[Tyrnador JumpStart]
* link:https://www.drivethrurpg.com/product/275399/Icy-Belly-of-Fillion-Manor[Icy Belly of Fillion Manor]

.OSR Resources
* link:http://www.drivethrurpg.com/product/139762/Barrowmaze-Complete[Barrowmaze Complete]
* link:http://www.barrowmaze.com/meatshields[Meatshields! Hireling and Henchman Generator]

== Character creation

=== Ancestries

// In this game, all PCs are human.
// There are different human cultures and ethnicities. 
Humans, dwarves, gnomes, elves and half-elves, half-orcs, and half-folk are all standard player ancestries.
// See SWADE for racial characteristics.

// NOTE: Elves are powerful - consult the GM if you want to play an elf, but do not get your hopes up.

=== Traits

As per SWADE.
Allocate 12 skills points.


By default a character knows one language per Smarts die type, starting with his native language.
For example, a character with Smarts d8, knows three languages.

NOTE: The *Reputation* trait represents the fame of the character. 
Your _Reputation_ starts at 0, unless it is modified by Edges and Hindrances.

=== Gear

Characters start with a set of clothes, a backpack, and all the gear they can buy with their starting money, equal to 500 cp. 


== Check for wandering monsters
Draw a card from the Action Deck, one per group of heroes (in case they split up).
A random encounter happens only with a Club or a Joker.
If the encounter has already happened, ignore it unless the encounter is
marked as Repeatable. 

NOTE: Not all encounters are with
creatures.

An adventure will have a table of Wandering Monsters, based on a card drawn from the Action Deck.

The unit of measure is the abstract “room”, which means the time an average party of adventurers needs to carefully explore one room. 

In the wilderness, you can consider it equal to one “encounter”. 

For ease of use, draw a card for every room the heroes explore, alternately checking for lights and one for wandering monsters.


== Illumination
The GM uses the illumination rules of Savage Worlds and
the following rules:

=== Light Checks
The GM will ask you to make a Light Check for every perishable source of light you have (e.g., torches and lanterns). 

. Draw a card from the Action Deck.
On a club, cancel a Durability point from your source of light. 

If the Durability drops to zero, the light source is exhausted. 

You can refill a lantern using an oil flask, restoring Durability to the maximum.

[cols="1,2"]
|===
| Torch | Durability 1
| Lantern | Durability 2
|===

=== Snuff Out Checks

In a dramatic situation (e.g., combat or chase), a character who is holding a light source must
check to if he drops the light whenever one of the following conditions arise:

* the character rolls a 1 on a Trait roll
* the character is hit hard (i.e., at least Shaken by a damaging effect)

The player draws a card from the Action Deck. 
On a club, the light falls and is extinguished. 
You can light it again.
However, if the club is also a face card, the lantern breaks.


=== Making Light in Darkness 

A character with a torch or lantern and flint and steel can light a source of light in two rounds, one with an Agility roll. 
Without flint and steel, you can try with two stones, but this requires five minutes and a Survival (-2) roll.
The cantrip power can light a torch or a lantern in one round.

== Phases of the game

A typical game is divided into two phases: the _adventuring phase_, which is where the meat of the scenario happens, and the _downtime phase_, which is at the end of the scenario and before the start of the next adventuring phase.

// === Adventure phase









////
== Light and darkness

Darkness:: 
Most dungeons are Pitch Darkness (-6 to most actions). 
A candle, torch, or lantern is considered enough lighting (i.e., no illumination penalties).
Duration:: 
A candle, torch, and lantern last a variable amount of time, represented by the usage die.
+
[cols="30%,70%"]
|===
| Light source | Usage die 

| Candle 
a| d8 + 
Candle blows out if you run or roll snake eyes
| Lantern | d8 
| Torch | d6 

|===

Light check::
Each time the group enters a new room after the first, the character holding the
source of light rolls the usage die. 
On a result of 1, the usage die becomes a d4. + 
When the usage die is a d4 and you roll a 1, the light goes out.

Area:: 
In most cases,the source of light affects all the room/area. 
Torches and lanterns also apply Dim Lighting to adjacent rooms and areas (i.e. a -2 modifier to most actions) assuming there are no other sources of light.
////

== Reputation

In game terms, a character's fame (or notoriety) is handled through the Reputation score.
Reputation measures the effect on the world of the adventurer's deeds and how these deeds are reported and then viewed by others.
The Reputation score begins at zero.
It increases as the character completes adventures and performs actions that others recognize. 

In game terms, whenever a character makes a Persuasion roll, you can use his Reputation score instead of the result, if the Reputation score is higher.

NOTE: The reputation of a character isn not universally known.
If a character is outside his typical area of operation, the GM can decide that the character's Reputation is not known and does not apply.

.Notoriety
****
You can have a bad reputation.
If you have a Reputation score below zero, you subtract the Reputation score from the character's Persuasion trait rolls.
On the other hand, if you have a negative Reputation score, you add the absolute value of the Reputation as a bonus to Intimidation rolls. 
These penalties and bonuses assume that you are interacting with NPCs that know of the character's bad reputation.
****


== Resting and healing

NOTE: For the purpose of natural (non-magical) healing, ignore the Golden Hour rules from SWADE.

To recover from wounds or fatigue, a character must take a proper _rest_.
A rest is an eight-hour period during which the characters make camp, eat, sleep, repair armor, memorize spells, etc.
// undisturbed??

To take a formal _rest_, the character consumes 1 quality of ration (food or the equivalent). 
If you have no rations, you do not benefit from the effects of the _rest_.
In addition, consult the Hunger and Thirst rules (SWADE p128 and 129, respectively) and apply them as you see fit.

At the end of an undisturbed period of rest, the heroes can make a Healing roll.
You use the Healing of the designated party healer (this is typically the character who has the best Healing roll).
The character recovers one Wound (or Fatigue level, based on the player's choice) per success and raise.
The you can recover up to three Wounds or Fatigue levels in total (e.g., if you have a success and three raises on the Healing roll, you only recover 3). 
You can combine Wounds and Fatigue as you wish.
Every healing roll can receive only one Support from another character.
The roll is subject to the normal Wounds penalties, both from the healer and from the patient.

=== Characters with the arcane backgrounds

Arcane Backgrounds also recover all their Power Points at the end of the Rest.
Interrupted Rest. 
If a Rest is interrupted once (by wandering monsters or similar) you still benefit from it, but if there are two interruptions or more, it is disrupted, no Wounds are healed or Power Points recovered, and the party must start another Rest from scratch (and consume another Ration).

=== Guards
By default, it is assumed that one hero at time is on guard duty during Rests, this doesn't hinder his ability to recover. 
If players take double turns with heroes, the GM can apply a penalty to the Healing roll (from -1 to -2).

=== Resting in civilized areas 
While resting in civilized areas the same rules above apply, but with no risk of wandering monsters, obviously. 
During the Downtime Phase, instead, when the party can freely rest, they recover all Wounds, Fatigue levels and Power Points.


== Money, wealth, and loot

As per the FC, $1 in Savage Worlds terms is 1 gold piece (FC p46).

1 gold piece = 10 silver pieces = 100 copper pieces 

Use the FC equipment tables for prices.

Use the expenses for Lifestyle for each character. 
Have each character specify their Lifestyle at character creation.
Lifestyle can change over the course of an adventurer's career.



// TFV - Characters start with a set of clothes, a backpack and all the gear they can buy with their starting money, equal to 500 cp.

// G&G - Currency comes as coins. Coins can be made of copper, silver, gold or platinum. Silver is the default and all prices are in silver pieces, or sp. One platinum piece (or pp) is ten gold pieces (or gp); one gold piece is ten silver pieces (or sp); one silver piece is ten copper pieces (or cp).


== Modified edges

=== Arcane Background

.The following Arcane Backgrounds are available to PCs: 
* Magic
* Miracles

////
.The following Arcane Backgrounds (from FC) are available to PCs: 
* Cleric
* Druid
* Sorcerer
* Wizard
////
// * Alchemist
// * Bard
// * Illusionist

=== New Power
A character with the magic arcane background can acquire the New Power Edge only if they have an Arcane Laboratory of adequate Rank available. 
A character with the magic miracles background can take powers above Novice Rank only if they have performed a proper quest or built/improved an site of veneration (that is, something akin to an altar) to their god(s).
//A wizard or sorcerer can acquire the New Power Edge only if they have an Arcane Laboratory of adequate Rank available. 
//A cleric or druid can take powers above Novice Rank only if they have performed a proper quest or built/improved an site of veneration (that is, something akin to an altar) to their god(s).
//  (see Game Master Guide page 71)

IMPORTANT: In this setting, this Edge only grants one new power.